path:
  ckpt_path: "/content/drive/MyDrive/voice_data/char_vlsp_fs2/ckpt/"
  log_path: "/content/drive/MyDrive/voice_data/char_vlsp_fs2/log/"
  result_path: "/content/drive/MyDrive/voice_data/char_vlsp_fs2/result/"
optimizer:
  batch_size: 32
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: []
  anneal_rate: 1.0
step:
  total_step: 900000
  log_step: 1000
  synth_step: 10000
  val_step: 10000
  save_step: 20000
